server:
  port: 9090

spring:
  profiles:
    active: local
    
  application:
    name: ranking-batch
    
  config:
    import:
      - jpa.yml
      - logging.yml
      - monitoring.yml
    
  batch:
    job:
      enabled: false  # 자동 실행 방지
    jdbc:
      initialize-schema: always  # Spring Batch 테이블 자동 생성
      table-prefix: BATCH_
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      
# 배치 설정
batch:
  chunk-size: 1000
  page-size: 1000
  skip-limit: 100
  
# 랭킹 가중치 기본값
ranking:
  weights:
    view: 0.1
    like: 0.2
    order: 0.7
    
---
spring:
  config:
    activate:
      on-profile: local
      
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      
logging:
  level:
    com.loopers.batch: DEBUG
    org.springframework.batch: DEBUG
    
---
spring:
  config:
    activate:
      on-profile: prod
      
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      
logging:
  level:
    com.loopers.batch: INFO
    org.springframework.batch: WARN
